---
title: "Prep counts from StringTie output for use with DESeq2"
author: "Enoch Ng'oma"
date: "7/19/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(DESeq2)
library(dplyr)
library(stringr)
library(sva)
library(ggplot2)

set.seed(38142903)
```

# Load gene count matrix and labels

```{r}
# Read in data frame and fill in empty spaces in column 2 with value in 1
pl3c <- read.csv("../../processed/S03_short_ballG/gene_count_matrix.csv", 
                 stringsAsFactors = FALSE)

rownames(pl3c) <- pl3c[,1]
pl3c[,1] <- NULL
countdata <- pl3c
colnames(countdata) = sub("\\.","",colnames(countdata)) #regex escape the escape
countdata <- as.matrix(countdata)

phenDat <- read.csv("../../processed/describe_samples_batch.csv", stringsAsFactors = FALSE)
names(phenDat)[1]<-"ids"
phenDat <- phenDat %>%
  select(ids,treatment,tissue,group)

rownames(phenDat) <- phenDat[,1]
phenDat[,1] <- NULL
rownames(phenDat) = sub("\\-","",rownames(phenDat)) 

# Check all sample IDs in colData are also in CountData and match their orders
all(rownames(phenDat) %in% colnames(countdata))
countdata <- countdata[, rownames(phenDat)]
all(rownames(phenDat) == colnames(countdata))

phenDat$group <- as.factor(phenDat$group)
phenDat$treatment <- as.factor(phenDat$treatment)
phenDat$tissue <- as.factor(phenDat$tissue)
write.csv(phenDat, "../../processed/phenotypes.csv", row.names = TRUE)
```

# Control for batch effects with sva

```{r}

dds <- DESeqDataSetFromMatrix(countData = countdata,
                              colData = phenDat, 
                              design = ~ tissue*treatment)


dds.sva <- estimateSizeFactors(dds)
dat.sva <- counts(dds.sva, normalized=TRUE)
cc.c <- rowSums(dat.sva)

#remove all genes with 0s for all samples
dat.sva <- dat.sva[which(cc.c>0),]

phenDat.sva <- phenDat
names(phenDat.sva)[3]<-"batch"
#cbind(phenDat.sva, colnames(dat.sva))

mod <- model.matrix(~as.factor(treatment)* 
                              as.factor(tissue) + 
                              as.factor(batch), 
                              data=phenDat.sva)

mod0 <- model.matrix(~as.factor(batch), data=phenDat.sva) 

# calculate number of surrogate variables
n.sv <- num.sv(dat.sva, mod, method = "be")
print(c("Calculated number of significant SVs = ", n.sv))

svobj <- svaseq(dat.sva, mod, mod0, n.sv=n.sv) 

phenDat.sva$SV1 <- svobj$sv[,1]

# countData colnames() must be identical to colData rownames()
all(rownames(phenDat.sva) %in% colnames(countdata))
countdata <- countdata[, rownames(phenDat.sva)]
all(rownames(phenDat.sva) == colnames(countdata))

# Write a background file for DE and GO analysis
write.csv(countdata, "../../processed/DESEQ/normExpr_countData.csv", row.names = TRUE)
write.csv(phenDat.sva, "../../processed/DESEQ/sampleDat_with_SV.csv")
```


