---
title: "Compare gene count tables"
author: "Enoch Ng'oma"
date: "7/19/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(DESeq2)
library(dplyr)
library(stringr)
library(sva)
library(ggplot2)
library(limma)
library(RColorBrewer)

set.seed(38142903)
```

```{r}
# Read in data frame and fill in empty spaces in column 2 with value in 1
cdat1 <- read.csv("../../processed/DESEQ/Expr_countData.csv", stringsAsFactors = FALSE)

#dds.g <- which(duplicated(cdat1$gene_id0))
#cdat1[cdat1$gene_id0==cdat1$gene_id0[dds.g[6]],1:6]

cdat1$gene_id <- ifelse(cdat1$gene_id == "", cdat1$gene_id0, cdat1$gene_id) 
cdat1 <- cdat1[c(2, 1, 3:57)]

rownames(cdat1) <- cdat1[,1]
cdat1[,1:3] <- NULL

cdat2 <- read.csv("../../processed/longProtocol/Old-gene_count_matrix.csv", row.names="gene_id")

cdat3 <- read.csv("../../processedshortProtocol/S03_short_ballG/gene_count_matrix.csv", row.names="gene_id")

```



```{r}

# Reformat column names
countdata<-cdat3
names(countdata) = sub("\\.","",names(countdata)) #regex escape the escape
countdata <- as.matrix(countdata)

phenDat <- read.csv("../../processed/describe_samples_batch.csv", stringsAsFactors = FALSE)
names(phenDat)[1]<-"ids"
phenDat <- phenDat %>%
  select(ids,treatment,tissue,group)

rownames(phenDat) <- phenDat[,1]
phenDat[,1] <- NULL
rownames(phenDat) = sub("\\-","",rownames(phenDat)) 
#colData <- pData(phenDat)[,c("treatment","tissue")]
#phenDat <- as.matrix(phenDat)

# Check all sample IDs in colData are also in CountData and match their orders
all(rownames(phenDat) %in% colnames(countdata))
countdata <- countdata[, rownames(phenDat)]
all(rownames(phenDat) == colnames(countdata))

phenDat$group <- as.factor(phenDat$group)
phenDat$treatment <- as.factor(phenDat$treatment)
phenDat$tissue <- as.factor(phenDat$tissue)
```

# Model with treatment and tissue
# DESeq vs Ballgown, see https://support.bioconductor.org/p/107011/

```{r}
# Create a DESeqDataSet from count matrix and labels
dds <- DESeqDataSetFromMatrix(countData = countdata,
                              colData = phenDat, 
                              design = ~ tissue + treatment)

colData(dds)$treatment <- factor(colData(dds)$treatment,
                                 levels = c("C","DR","HS"))


```


# Control for batch effects with sva

```{r}
dds.sva <- estimateSizeFactors(dds)
dat.sva <- counts(dds.sva, normalized=TRUE)
cc.c <- rowSums(dat.sva)

#remove all genes with 0s for all samples
dat.sva <- dat.sva[which(cc.c>0),]

#phenDat.sva <- read.csv("../../processed/describe_samples_batch.csv", stringsAsFactors = FALSE)
phenDat.sva <- phenDat
names(phenDat.sva)[3]<-"batch"
#cbind(phenDat.sva, colnames(dat.sva))

mod <- model.matrix(~as.factor(treatment)* 
                              as.factor(tissue) + 
                              as.factor(batch), 
                              data=phenDat.sva)

mod0 <- model.matrix(~as.factor(batch), data=phenDat.sva) 

# calculate number of surrogate variables
n.sv <- num.sv(dat.sva, mod, method = "be")
print(c("Calculated number of significant SVs = ", n.sv))

svobj <- svaseq(dat.sva, mod, mod0, n.sv=n.sv) 

phenDat.sva$SV1 <- svobj$sv[,1]
phenDat.sva$SV2 <- svobj$sv[,2]

head(phenDat.sva, 3)

ggplot(phenDat.sva, aes(x=SV1, y=SV2)) +
  geom_point(alpha=1/5, size=3)

```


```{r}
cdat1 <- read.csv("../../processed/longProtocol/gene_count_matrix_pl3c.csv", stringsAsFactors = FALSE)

dds.g <- which(duplicated(cdat1$gene_id0))
#cdat1[cdat1$gene_id0==cdat1$gene_id0[dds.g[6]],1:6]
dd.mst <- cdat1$gene_id0[dds.g]


cdat1$gene_id <- ifelse(cdat1$gene_id == "", cdat1$gene_id0, cdat1$gene_id) 
cdat1 <- cdat1[c(2, 1, 3:57)]
rownames(cdat1) <- cdat1[,1]

#check those that are given FBgn by stringtie
cdat1$id <- rownames(cdat1)
cdat2$id <- rownames(cdat2)
cdat3$id <- rownames(cdat3)

mm <- merge(cdat1,cdat3,by='id')
mmd<-mm[,5:58]-mm[,59:112]
ss <- rowSums(mmd)
which.min(ss)
mm[673,]

mm.dif <- mm[which(ss!=0),]
set.dupM <- which(mm.dif$gene_id0 %in% dd.mst)
mm.dif <- mm.dif[-set.dupM,]
mm.dif<- mm.dif[-which(mm.dif$gene_id1!=""),]

mm.sm<-mm.dif[,5:58]-mm.dif[,59:112]
which.max(rowSums(mm.sm))
mm.dif[41,1:10]
#should be low in ovaries- flybase more consistent with ref set


ww.13<- which(!(cdat1$id %in% cdat3$id))
grep("FB",cdat1$id[ww.13])

ww.31<- which(!(cdat3$id %in% cdat1$id))
ww.y<-which(cdat3$id[ww.31] %in% cdat1$gene_id1)
cdat3$id[ww.31][-ww.y]
```