---
title: "Base Population analysis with DESeq2"
author: "Enoch Ng'oma"
date: "10/21/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(DESeq2)
library(dplyr)
library(stringr)
library(ggplot2)
library(RColorBrewer)
```

# Expression count data

```{r}
countdata <- read.csv("../../processed/DESEQ/normExpr_countData.csv")
phenDat.sva <- read.csv("../../processed/DESEQ/sampleDat_with_SV.csv")
```

# Nested models

```{r}
# Fit DESeq models
dds.01 <- DESeqDataSetFromMatrix(countData = expr_viz, 
                                   colData = phenDat.sva, 
                                   design = ~ SV1 + batch + tissue + treatment)
dds_deseq.01 <- estimateSizeFactors(dds.01)
nc <- counts(dds_deseq.01, normalized=TRUE)
filter <- rowSums(nc >= 10) >= 2
dds_deseq.01 <- dds_deseq.01[filter,]
dds_deseq.01 <- estimateDispersions(dds_deseq.01, fitType = "local")
dds_deseq.01 <- nbinomWaldTest(dds_deseq.01, maxit = 1000, useOptim = TRUE)

resultsNames(dds_deseq.01)

# Look at the DESeq object
colData(dds_deseq.01)
save(dds_deseq.01, file="../../processed/DESEQ/dds_deseq01.Rda")

dds.02 <- DESeqDataSetFromMatrix(countData = expr_viz, 
                                   colData = phenDat.sva, 
                                   design = ~ SV1 + batch + tissue*treatment)

dds_deseq.02 <- estimateSizeFactors(dds.02)
nc <- counts(dds_deseq.02, normalized=TRUE)
filter <- rowSums(nc >= 10) >= 2
dds_deseq.02 <- dds_deseq.02[filter,]
dds_deseq.02 <- estimateDispersions(dds_deseq.02, fitType = "local")
dds_deseq.02 <- nbinomWaldTest(dds_deseq.02, maxit = 1000, useOptim = TRUE)
dds_deseq.02 <- dds_deseq.02[which(mcols(dds_deseq.02)$betaConv),]

resultsNames(dds_deseq.02)
colData(dds_deseq.02)

# Test if all values are equal
#which(all(dds_deseq.01 != dds_deseq.02))

# Test if objects are identical
identical(dds_deseq.01,dds_deseq.02)
save(dds_deseq.02, file="../../processed/DESEQ/dds_deseq.02.Rda")

# DEGs significant for effect of tissue 
lrt.tissue <- DESeq(dds.01, test="LRT", reduced=~ SV1 + batch + treatment)
lrt.tissue <- lrt.tissue[which(mcols(lrt.tissue)$fullBetaConv),]
lrt.tissue <- results(lrt.tissue, alpha = 0.05)

# DEGs significant for effect of treatment 
lrt.treatment <- DESeq(dds.01, test="LRT", reduced=~ SV1 + batch + tissue)
lrt.treatment <- lrt.treatment[which(mcols(lrt.treatment)$fullBetaConv),]
lrt.treatment <- results(lrt.treatment, alpha = 0.05)

# DEGs significant for effect of the interaction 
lrt.int <- DESeq(dds.02, test="LRT", reduced=~ SV1 + batch + tissue + treatment)
lrt.int <- lrt.int[which(mcols(lrt.int)$fullBetaConv),]
lrt.int <- results(lrt.int, alpha = 0.05)

# pairwise comparisions (treatment effect assuming interaction)
rr1 <- results(dds_deseq.02, contrast=c('tissue', "H","B"), alpha = 0.05)
rr2 <- results(dds_deseq.02, contrast=c('tissue', "O","B"), alpha = 0.05)
rr3 <- results(dds_deseq.02, contrast=c('tissue', "O","H"), alpha = 0.05)

# Get lists of DEGs
resSig_lrt.int <- subset(lrt.int, padj < 0.05)
summary(resSig_lrt.int)
sum(resSig_lrt.int$padj < 0.05, na.rm = TRUE)
resSig_lrt.int$Gene <- rownames(resSig_lrt.int)
resSig_lrt.int <- resSig_lrt.int[, c(7,1:6)]
(resSig_lrt.int <- resSig_lrt.int[order(resSig_lrt.int$padj), ])

resSig_lrt.tissue <- subset(lrt.tissue, padj < 0.05)
summary(resSig_lrt.tissue)
sum(lrt.tissue$padj < 0.05, na.rm = TRUE)
resSig_lrt.tissue$Gene <- rownames(resSig_lrt.tissue)
resSig_lrt.tissue <- resSig_lrt.tissue[, c(7,1:6)]
resSig_lrt.tissue <- resSig_lrt.tissue[order(resSig_lrt.tissue$padj), ]

resSig_lrt.treatment <- subset(lrt.treatment, padj < 0.05)
summary(resSig_lrt.treatment)
sum(lrt.treatment$padj < 0.05, na.rm = TRUE)
resSig_lrt.treatment$Gene <- rownames(resSig_lrt.treatment)
resSig_lrt.treatment <- resSig_lrt.treatment[, c(7,1:6)]
resSig_lrt.treatment <- resSig_lrt.treatment[order(resSig_lrt.treatment$padj), ]

write.csv(dds_deseq.02, "../../processed/DESEQ/dds_deseq.02.csv", row.names = FALSE)
write.csv(resSig_lrt.int, "../../processed/DESEQ/DEGs_lrt.int_0.05.csv", row.names = FALSE)
write.csv(resSig_lrt.tissue, "../../processed/DESEQ/DEGs_lrt.tissue_0.05.csv", row.names = FALSE)
write.csv(resSig_lrt.treatment, "../../processed/DESEQ/DEGs_lrt.treatment_0.05.csv", row.names = FALSE)

# Background list - all gene_ids for GO term enrichment
bList <- as.data.frame(rownames(pl3c))
write.csv(bList, "../../processed/DESEQ/gene_background_list.csv")
```

# pairwise comparisions (tissue effect, interaction model)

```{r}
ff1 <- results(dds_deseq.02, contrast=c('treatment', "C","DR"), alpha = 0.05)
ff2 <- results(dds_deseq.02, contrast=c('treatment', "C","HS"), alpha = 0.05)
ff3 <- results(dds_deseq.02, contrast=c('treatment', "DR","HS"), alpha = 0.05)
```

# Model with interaction

```{r}
dds.int <- DESeqDataSetFromMatrix(countData = countdata, 
                                  colData = phenDat.sva, 
                                  design = ~ SV1 + batch + tissue + treatment + tissue:treatment)

dds.deInt <- estimateSizeFactors(dds.int)
nc <- counts(dds.deInt, normalized=TRUE)
filter <- rowSums(nc >= 10) >= 2
dds.deInt <- dds.deInt[filter,]
dds.deInt <- estimateDispersions(dds.deInt, fitType = "local")
dds.deInt <- nbinomWaldTest(dds.deInt, maxit = 10000, useOptim = TRUE)

# dealing with autocorrelation: https://support.bioconductor.org/p/65091/
#dds_int <- DESeq(dds.int)

# Remove unconverged rows
dds.deInt <- dds.deInt[which(mcols(dds.deInt)$betaConv),]

# Look at the DESeq object
colData(dds.deInt)

# results for all terms

rr1 <- results(dds.deInt, contrast=c('tissue', "H","B"))
rr2 <- results(dds.deInt, contrast=c('tissue', "O","B"))
rr3 <- results(dds.deInt, contrast=c('tissue', "O","H"))

lrt.int <- DESeq(dds.int, test="LRT", reduced=~ SV1 + batch + tissue + treatment)
lrt.int <- results(lrt.int)


# Access results
res_int <- results(dds.deInt)
(resOrd_int <- res_int[order(res_int$padj), ])

save(dds.deInt, file = "../../processed/DESEQ/DEseq_sva_int.Rda")
load("../../processed/DESEQ/DEseq_sva_int.Rda")
# Basic tallies
summary(res_int)

# How many pvalues are less than 0.1
sum(res_int$padj < 0.1, na.rm = TRUE)

# Try alpha 0.05 (default is 0.1)
res05 <- results(dds.deInt, alpha=0.05) 
summary(res05)

# Boxplot of samples
par(mar=c(8,5,2,2))
boxplot(log10(assays(dds.deInt)[["cooks"]]), range=0, las=2)

# Merge with normalized count data
res.int_table <- merge(as.data.frame(res_int), 
                       as.data.frame(counts(dds.deInt, normalized=TRUE)), 
                       by="row.names", sort=FALSE)
names(res.int_table)[1] <- "Gene"

write.csv(resOrd_int, 
          "../../processed/DESEQ/DEseqSVA_int_resOrdered_padj.csv", row.names=TRUE)
```