---
title: "Prep counts from StringTie output for use with DESeq2"
author: "Enoch Ng'oma"
date: "7/19/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(DESeq2)
library(dplyr)
library(stringr)
library(sva)
library(ggplot2)
library(limma)
library(RColorBrewer)

set.seed(38142903)
```

# Load gene(/transcript) count matrix and labels

```{r}
# Read in data frame and fill in empty spaces in column 2 with value in 1
pl3c <- read.csv("../../processed/S03_short_ballG/gene_count_matrix.csv", 
                 stringsAsFactors = FALSE)

rownames(pl3c) <- pl3c[,1]
pl3c[,1] <- NULL
countdata <- pl3c
colnames(countdata) = sub("\\.","",colnames(countdata)) #regex escape the escape
countdata <- as.matrix(countdata)

phenDat <- read.csv("../../processed/describe_samples_batch.csv", stringsAsFactors = FALSE)
names(phenDat)[1]<-"ids"
phenDat <- phenDat %>%
  select(ids,treatment,tissue,group)

rownames(phenDat) <- phenDat[,1]
phenDat[,1] <- NULL
rownames(phenDat) = sub("\\-","",rownames(phenDat)) 

# Check all sample IDs in colData are also in CountData and match their orders
all(rownames(phenDat) %in% colnames(countdata))
countdata <- countdata[, rownames(phenDat)]
all(rownames(phenDat) == colnames(countdata))

phenDat$group <- as.factor(phenDat$group)
phenDat$treatment <- as.factor(phenDat$treatment)
phenDat$tissue <- as.factor(phenDat$tissue)
```

# Control for batch effects with sva

```{r}

dds <- DESeqDataSetFromMatrix(countData = countdata,
                              colData = phenDat, 
                              design = ~ tissue*treatment)


dds.sva <- estimateSizeFactors(dds)
dat.sva <- counts(dds.sva, normalized=TRUE)
cc.c <- rowSums(dat.sva)

#remove all genes with 0s for all samples
dat.sva <- dat.sva[which(cc.c>0),]

phenDat.sva <- phenDat
names(phenDat.sva)[3]<-"batch"
#cbind(phenDat.sva, colnames(dat.sva))

mod <- model.matrix(~as.factor(treatment)* 
                              as.factor(tissue) + 
                              as.factor(batch), 
                              data=phenDat.sva)

mod0 <- model.matrix(~as.factor(batch), data=phenDat.sva) 

# calculate number of surrogate variables
n.sv <- num.sv(dat.sva, mod, method = "be")
print(c("Calculated number of significant SVs = ", n.sv))

svobj <- svaseq(dat.sva, mod, mod0, n.sv=n.sv) 

phenDat.sva$SV1 <- svobj$sv[,1]

# countData colnames() must be identical to colData rownames()
all(rownames(phenDat.sva) %in% colnames(countdata))
countdata <- countdata[, rownames(phenDat.sva)]
all(rownames(phenDat.sva) == colnames(countdata))
```

# Nested models

```{r}
# Create a DESeqDataSet from count matrix and labels

dds.01 <- DESeqDataSetFromMatrix(countData = countdata, 
                                   colData = phenDat.sva, 
                                   design = ~ SV1 + batch + tissue + treatment)

dds.02 <- DESeqDataSetFromMatrix(countData = countdata, 
                                   colData = phenDat.sva, 
                                   design = ~ SV1 + batch + tissue*treatment)

# either run DESeq or do these three steps
dds_deseq.01 <- estimateSizeFactors(dds.01)
nc <- counts(dds_deseq.01, normalized=TRUE)
filter <- rowSums(nc >= 10) >= 2
dds_deseq.01 <- dds_deseq.01[filter,]
dds_deseq.01 <- estimateDispersions(dds_deseq.01, fitType = "local")
dds_deseq.01 <- nbinomWaldTest(dds_deseq.01, maxit = 1000, useOptim = TRUE)

dds_deseq.02 <- estimateSizeFactors(dds.02)
nc <- counts(dds_deseq.02, normalized=TRUE)
filter <- rowSums(nc >= 10) >= 2
dds_deseq.02 <- dds_deseq.02[filter,]
dds_deseq.02 <- estimateDispersions(dds_deseq.02, fitType = "local")
dds_deseq.02 <- nbinomWaldTest(dds_deseq.02, maxit = 1000, useOptim = TRUE)
dds_deseq.02 <- dds_deseq.02[which(mcols(dds_deseq.02)$betaConv),]

# Look at the DESeq object
colData(dds_deseq.01)
colData(dds_deseq.02)

# Effect of tissue 
lrt.tissue <- DESeq(dds.01, test="LRT", reduced=~ SV1 + batch + treatment)
lrt.tissue <- lrt.tissue[which(mcols(lrt.tissue)$fullBetaConv),]
lrt.tissue <- results(lrt.tissue, alpha = 0.05)

# Effect of treatment 
lrt.treatment <- DESeq(dds.01, test="LRT", reduced=~ SV1 + batch + tissue)
lrt.treatment <- lrt.treatment[which(mcols(lrt.treatment)$fullBetaConv),]
lrt.treatment <- results(lrt.treatment, alpha = 0.05)

# Effect of the interaction 
lrt.int <- DESeq(dds.02, test="LRT", reduced=~ SV1 + batch + tissue + treatment)
lrt.int <- lrt.int[which(mcols(lrt.int)$fullBetaConv),]
lrt.int <- results(lrt.int, alpha = 0.05)

# pairwise comparisions
rr1 <- results(dds_deseq.02, contrast=c('tissue', "H","B"), alpha = 0.05)
rr2 <- results(dds_deseq.02, contrast=c('tissue', "O","B"), alpha = 0.05)
rr3 <- results(dds_deseq.02, contrast=c('tissue', "O","H"), alpha = 0.05)

# Get list of DEGs
resSig_lrt.int <- subset(lrt.int, padj < 0.05)
summary(resSig_lrt.int)
sum(resSig_lrt.int$padj < 0.05, na.rm = TRUE)
write.table(resSig_lrt.int, "../../processed/DESEQ/resSig_lrt.int_0.05.xlsx", row.names=TRUE, sep="\t")

resSig_lrt.tissue <- subset(lrt.tissue, padj < 0.05)
summary(resSig_lrt.tissue)
sum(lrt.tissue$padj < 0.05, na.rm = TRUE)
write.table(resSig_lrt.tissue, "../../processed/DESEQ/resSig_lrt.tissue_0.05.xlsx", row.names=TRUE, sep="\t")

resSig_lrt.treatment <- subset(lrt.treatment, padj < 0.05)
summary(resSig_lrt.treatment)
sum(lrt.treatment$padj < 0.05, na.rm = TRUE)
write.table(resSig_lrt.treatment, "../../processed/DESEQ/resSig_lrt.treatment_0.05.xlsx", row.names=TRUE, sep="\t")


# List for comparisons
resSig_HB <- subset(rr1, padj < 0.05)
summary(resSig_HB)
sum(resSig_HB$padj < 0.05, na.rm = TRUE)
write.table(resSig_HB, "../../processed/DESEQ/resSig_HB_0.05.xlsx", row.names=TRUE, sep="\t")

resSig_OB <- subset(rr2, padj < 0.05)
summary(resSig_OB)
sum(resSig_OB$padj < 0.05, na.rm = TRUE)
write.table(resSig_OB, "../../processed/DESEQ/resSig_OB_0.05.xlsx", row.names=TRUE, sep="\t")

resSig_OH <- subset(rr3, padj < 0.05)
summary(resSig_OH)
sum(resSig_OH$padj < 0.05, na.rm = TRUE)
write.table(resSig_OH, "../../processed/DESEQ/resSig_OH_0.05.xlsx", row.names=TRUE, sep="\t")

```

# PCA

```{r}

vsd.01 <- varianceStabilizingTransformation(dds_deseq.01, blind = TRUE)
vsd.02 <- varianceStabilizingTransformation(dds_deseq.02, blind = TRUE)

print(plotPCA(vsd.01, intgroup=c("treatment", "tissue")))
plotPCA(vsd.01, intgroup=c("tissue"), returnData=FALSE)
plotPCA(vsd.01, intgroup=c("treatment"), returnData=FALSE)

print(plotPCA(vsd.02, intgroup=c("treatment", "tissue")))
plotPCA(vsd.02, intgroup=c("tissue"), returnData=FALSE)
plotPCA(vsd.02, intgroup=c("treatment"), returnData=FALSE)
```



```{r}
## Merge with normalized count data
res.dds_table <- merge(as.data.frame(res.dds), 
                       as.data.frame(counts(dds_deseq, normalized=TRUE)), 
                       by="row.names", sort=FALSE)
names(res.dds_table)[1] <- "Gene"

#save(res.dds, file = "../../processed/DESEQ/res.dds.Rda")
#save(dds_deseq, file = "../../processed/DESEQ/dds_deseq.Rda")
#save(res.dds_table, file = "../../processed/DESEQ/DEseqSVA_Noint_resOrdered_padj.Rda")

#write.csv(res.dds_table, 
          #"../../processed/DESEQ/DEseqSVA_Noint_resOrdered_padj.csv", row.names=TRUE)

load("../../processed/DESEQ/res.dds.Rda")
load("../../processed/DESEQ/dds_deseq.Rda")
load("../../processed/DESEQ/DEseqSVA_Noint_resOrdered_padj.Rda")

# Examine plot of p-values
hist(res.dds$pvalue, breaks=50, col="grey")

# Examine independent filtering
metadata(res.dds)$filterThreshold

plot(metadata(res.dds)$filterNumRej, type="b", xlab="quantiles of baseMean", ylab="number of rejections")
```

# MA plot

```{r}
load("../../processed/DESEQ/DEseqSVA_Noint_resOrdered_padj.Rda")

# Could do with built-in DESeq2 function:
DESeq2::plotMA(dds_deseq, ylim=c(-5,5))

# Alternatively
maplot <- function (res.dds_table, thresh=0.05, labelsig=TRUE, textcx=1, ...) {
  with(res.dds_table, plot(baseMean, log2FoldChange, pch=20, cex=.5, log="x", ...))
  with(subset(res.dds_table, padj<thresh), points(baseMean, log2FoldChange, col="red", pch=20, cex=1.5))
  if (labelsig) {
    require(calibrate)
    with(subset(res.dds_table, padj<thresh), textxy(baseMean, log2FoldChange, labs="Gene", cex=textcx, col=2))
  }
}
png("diffexpr-maplot.png", 1500, 1000, pointsize=20)
maplot(res.dds_table, ylim=c(-2,2), main="MA Plot")
dev.off()
```

# Volcano plot

```{r}
load("../../processed/DESEQ/DEseqSVA_Noint_resOrdered_padj.Rda")

par(mar=c(5,5,5,5), cex=1.0, cex.main=1.4, cex.axis=1.4, cex.lab=1.4)

topT <- as.data.frame(res.dds_table)

#Adjusted P values (FDR Q values)
with(topT, plot(log2FoldChange, -log10(padj), pch=20, main="Volcano plot", cex=1.0, xlab=bquote(~Log[2]~fold~change), ylab=bquote(~-log[10]~Q~value)))

with(subset(topT, padj<0.05 & abs(log2FoldChange)>2), points(log2FoldChange, -log10(padj), pch=20, col="red", cex=0.5))

with(subset(topT, padj<0.05 & abs(log2FoldChange)>2), text(log2FoldChange, -log10(padj), labels=subset(rownames(topT), topT$padj<0.05 & abs(topT$log2FoldChange)>2), cex=0.8, pos=3))

#Add lines for absolute FC>2 and P-value cut-off at FDR Q<0.05
abline(v=0, col="black", lty=3, lwd=1.0)
abline(v=-2, col="black", lty=4, lwd=2.0)
abline(v=2, col="black", lty=4, lwd=2.0)
abline(h=-log10(max(topT$pvalue[topT$padj<0.05], na.rm=TRUE)), col="black", lty=4, lwd=2.0)
```

```{r}
#dev.off()
with(res.dds_table, plot(log2FoldChange, -log10(pvalue), pch=20, main="Volcano plot", xlim=c(-5,5), ylim=c(0,25)))

# Add colored points: red if padj<0.05, orange of log2FC>1, green if both)
with(subset(res.dds_table, padj<.05 ), points(log2FoldChange, -log10(pvalue), pch=20, col="red"))
with(subset(res.dds_table, abs(log2FoldChange)>1), points(log2FoldChange, -log10(pvalue), pch=20, col="orange"))
with(subset(res.dds_table, padj<.05 & abs(log2FoldChange)>1), points(log2FoldChange, -log10(pvalue), pch=20, col="green"))

# Label points with the textxy function from the calibrate plot
library(calibrate)
with(subset(res.dds_table, padj<.05 & abs(log2FoldChange)>1), textxy(log2FoldChange, -log10(pvalue), labs=Gene, cex=.8))
```

# Look at highly DE genes

```{r}
highDown <- which(topT$log2FoldChange < -5)
topT[highDown,]

highUp <- which(topT$log2FoldChange > 5)
topT[highUp,]
```

# Contrast C vs DR

```{r}
# Comparisons across treatment levels
resultsNames(dds_deseq)

cdr.dds <- results(dds_deseq, contrast=c("treatment","C","DR"))
mcols(cdr.dds) # mcols = metadata columns, i.e. element-wise metadata
(resOrd_cdrdds <- cdr.dds[order(cdr.dds$padj), ])
write.csv(resOrd_cdrdds, 
          "../../processed/DESEQ/CvDR_DEseqSVA_dds_resOrdered_padj.csv", row.names=TRUE)


# MA plot
maplot <- function (resOrd_cdrdds, thresh=0.05, labelsig=TRUE, textcx=1, ...) {
  with(resOrd_cdrdds, plot(baseMean, log2FoldChange, pch=20, cex=.5, log="x", ...))
  with(subset(resOrd_cdrdds, padj<thresh), points(baseMean, log2FoldChange, col="red", pch=20, cex=1.5))
  if (labelsig) {
    require(calibrate)
    with(subset(resOrd_cdrdds, padj<thresh), textxy(baseMean, log2FoldChange, labs="Gene", cex=textcx, col=2))
  }
}
png("diffexpr-maplot.png", 1500, 1000, pointsize=20)
maplot(resOrd_cdrdds, ylim=c(-2,2), main="MA Plot C vs DR")
dev.off()


# Volcano
par(mar=c(5,5,5,5), cex=1.0, cex.main=1.4, cex.axis=1.4, cex.lab=1.4)

cdr <- as.data.frame(resOrd_cdrdds)

#Adjusted P values (FDR Q values)
with(cdr, plot(log2FoldChange, -log10(padj), pch=20, main="Volcano plot", cex=1.0, xlab=bquote(~Log[2]~fold~change), ylab=bquote(~-log[10]~Q~value)))

with(subset(cdr, padj<0.05 & abs(log2FoldChange)>2), points(log2FoldChange, -log10(padj), pch=20, col="red", cex=0.5))

with(subset(cdr, padj<0.05 & abs(log2FoldChange)>2), text(log2FoldChange, -log10(padj), labels=subset(rownames(cdr), cdr$padj<0.05 & abs(cdr$log2FoldChange)>2), cex=0.8, pos=3))

#Add lines for absolute FC>2 and P-value cut-off at FDR Q<0.05
abline(v=0, col="black", lty=3, lwd=1.0)
abline(v=-2, col="black", lty=4, lwd=2.0)
abline(v=2, col="black", lty=4, lwd=2.0)
abline(h=-log10(max(cdr$pvalue[cdr$padj<0.05], na.rm=TRUE)), col="black", lty=4, lwd=2.0)
```

# Contrast C vs HS

```{r}
hs.dds <- results(dds_deseq, contrast=c("treatment","C","HS"))
(resOrd_hsdds <- hs.dds[order(hs.dds$padj), ])

write.csv(resOrd_hsdds, 
          "../../processed/DESEQ/CvHS_DEseqSVA_dds_resOrdered_padj.csv",
          row.names=TRUE)

# MA plot
maplot <- function (resOrd_hsdds, thresh=0.05, labelsig=TRUE, textcx=1, ...) {
  with(resOrd_hsdds, plot(baseMean, log2FoldChange, pch=20, cex=.5, log="x", ...))
  with(subset(resOrd_hsdds, padj<thresh), points(baseMean, log2FoldChange, col="red", pch=20, cex=1.5))
  if (labelsig) {
    require(calibrate)
    with(subset(resOrd_hsdds, padj<thresh), textxy(baseMean, log2FoldChange, labs="Gene", cex=textcx, col=2))
  }
}
png("diffexpr-maplot.png", 1500, 1000, pointsize=20)
maplot(resOrd_hsdds, ylim=c(-2,2), main="MA Plot C vs HS")
dev.off()

# Volcano
par(mar=c(5,5,5,5), cex=1.0, cex.main=1.4, cex.axis=1.4, cex.lab=1.4)

hs <- as.data.frame(resOrd_hsdds)

#Adjusted P values (FDR Q values)
with(hs, plot(log2FoldChange, -log10(padj), pch=20, main="Volcano plot", cex=1.0, xlab=bquote(~Log[2]~fold~change), ylab=bquote(~-log[10]~Q~value)))

with(subset(hs, padj<0.05 & abs(log2FoldChange)>2), points(log2FoldChange, -log10(padj), pch=20, col="red", cex=0.5))

with(subset(hs, padj<0.05 & abs(log2FoldChange)>2), text(log2FoldChange, -log10(padj), labels=subset(rownames(hs), hs$padj<0.05 & abs(hs$log2FoldChange)>2), cex=0.8, pos=3))

#Add lines for absolute FC>2 and P-value cut-off at FDR Q<0.05
abline(v=0, col="black", lty=3, lwd=1.0)
abline(v=-2, col="black", lty=4, lwd=2.0)
abline(v=2, col="black", lty=4, lwd=2.0)
abline(h=-log10(max(hs$pvalue[hs$padj<0.05], na.rm=TRUE)), col="black", lty=4, lwd=2.0)
```

# Contrast DR vs HS

```{r}
dh.dds <- results(dds_deseq, contrast=c("treatment","DR","HS"))
(resOrd_dhdds <- dh.dds[order(dh.dds$padj), ])

write.csv(resOrd_dhdds, 
          "../../processed/DESEQ/DRvHS_DEseqSVA_dds_resOrdered_padj.csv",
          row.names=TRUE)

# MA plot
maplot <- function (resOrd_dhdds, thresh=0.05, labelsig=TRUE, textcx=1, ...) {
  with(resOrd_dhdds, plot(baseMean, log2FoldChange, pch=20, cex=.5, log="x", ...))
  with(subset(resOrd_dhdds, padj<thresh), points(baseMean, log2FoldChange, col="red", pch=20, cex=1.5))
  if (labelsig) {
    require(calibrate)
    with(subset(resOrd_dhdds, padj<thresh), textxy(baseMean, log2FoldChange, labs="Gene", cex=textcx, col=2))
  }
}
png("diffexpr-maplot.png", 1500, 1000, pointsize=20)
maplot(resOrd_dhdds, ylim=c(-2,2), main="MA Plot DR vs HS")
dev.off()

# Volcano
par(mar=c(5,5,5,5), cex=1.0, cex.main=1.4, cex.axis=1.4, cex.lab=1.4)

drhs <- as.data.frame(resOrd_dhdds)

#Adjusted P values (FDR Q values)
with(drhs, plot(log2FoldChange, -log10(padj), pch=20, main="Volcano plot", cex=1.0, xlab=bquote(~Log[2]~fold~change), ylab=bquote(~-log[10]~Q~value)))

with(subset(drhs, padj<0.05 & abs(log2FoldChange)>2), points(log2FoldChange, -log10(padj), pch=20, col="red", cex=0.5))

with(subset(drhs, padj<0.05 & abs(log2FoldChange)>2), text(log2FoldChange, -log10(padj), labels=subset(rownames(drhs), drhs$padj<0.05 & abs(drhs$log2FoldChange)>2), cex=0.8, pos=3))

#Add lines for absolute FC>2 and P-value cut-off at FDR Q<0.05
abline(v=0, col="black", lty=3, lwd=1.0)
abline(v=-2, col="black", lty=4, lwd=2.0)
abline(v=2, col="black", lty=4, lwd=2.0)
abline(h=-log10(max(drhs$pvalue[drhs$padj<0.05], na.rm=TRUE)), col="black", lty=4, lwd=2.0)
```




# Model with interactions

```{r}
dds.int <- DESeqDataSetFromMatrix(countData = countdata, 
                                  colData = phenDat.sva, 
                                  design = ~ SV1 + batch + tissue + treatment + tissue:treatment)

dds.deInt <- estimateSizeFactors(dds.int)
nc <- counts(dds.deInt, normalized=TRUE)
filter <- rowSums(nc >= 10) >= 2
dds.deInt <- dds.deInt[filter,]
dds.deInt <- estimateDispersions(dds.deInt, fitType = "local")
dds.deInt <- nbinomWaldTest(dds.deInt, maxit = 10000, useOptim = TRUE)

# dealing with autocorrelation: https://support.bioconductor.org/p/65091/
#dds_int <- DESeq(dds.int)

# Remove unconverged rows
dds.deInt <- dds.deInt[which(mcols(dds.deInt)$betaConv),]

# Look at the DESeq object
colData(dds.deInt)

# results for all terms

rr1 <- results(dds.deInt, contrast=c('tissue', "H","B"))
rr2 <- results(dds.deInt, contrast=c('tissue', "O","B"))
rr3 <- results(dds.deInt, contrast=c('tissue', "O","H"))

lrt.int <- DESeq(dds.int, test="LRT", reduced=~ SV1 + batch + tissue + treatment)
lrt.int <- results(lrt.int)


# Access results
res_int <- results(dds.deInt)
(resOrd_int <- res_int[order(res_int$padj), ])

save(dds.deInt, file = "../../processed/DESEQ/DEseq_sva_int.Rda")
load("../../processed/DESEQ/DEseq_sva_int.Rda")
# Basic tallies
summary(res_int)

# How many pvalues are less than 0.1
sum(res_int$padj < 0.1, na.rm = TRUE)

# Try alpha 0.05 (default is 0.1)
res05 <- results(dds.deInt, alpha=0.05) 
summary(res05)

# Boxplot of samples
par(mar=c(8,5,2,2))
boxplot(log10(assays(dds.deInt)[["cooks"]]), range=0, las=2)

# Merge with normalized count data
res.int_table <- merge(as.data.frame(res_int), 
                       as.data.frame(counts(dds.deInt, normalized=TRUE)), 
                       by="row.names", sort=FALSE)
names(res.int_table)[1] <- "Gene"

write.csv(resOrd_int, 
          "../../processed/DESEQ/DEseqSVA_int_resOrdered_padj.csv", row.names=TRUE)
```

# Look at highly DE genes

```{r}
topDE <- as.data.frame(res.int_table)

highDown <- which(topDE$log2FoldChange < -5)
topDE[highDown,]

highUp <- which(topDE$log2FoldChange > 5)
topDE[highUp,]
```

# Contrasts

```{r}
# arguments 'name' and 'contrast' to results() are the same

resultsNames(dds.deInt)

# C vs DR
cdr.int <- results(dds.deInt, contrast=c("treatment","DR","C"))
#same as:
cdr.in <- results(dds.deInt, name = "treatment_DR_vs_C")

mcols(cdr.int) # mcols = metadata columns, i.e. element-wise metadata
(resOrd_cdrint <- cdr.int[order(cdr.int$padj), ])

# Get more info onresults columns
mcols(cdr.int)$description

write.csv(resOrd_cdrint, 
          "../../processed/DESEQ/treatment_DR_vs_C.csv", row.names=TRUE)

resSig_cdr <- subset(resOrd_cdrint, padj < 0.1)
summary(resSig_cdr)
sum(resSig_cdr$padj < 0.1, na.rm = TRUE)

# Log fold change shrinkage for visualization and ranking
# Ref. https://www.biorxiv.org/content/early/2018/04/17/303255 #for fewer NAs in padj??.
library(apeglm)
res_cdr_LFC <- lfcShrink(dds.deInt, coef="treatment_DR_vs_C", type="apeglm") 
res_cdr_LFC

# Compare MA plots
plotMA(cdr.int, ylim=c(-5,5))
plotMA(res_cdr_LFC, ylim=c(-5,5))


#C vs HS
hs.int <- results(dds_deseq, contrast=c("treatment","C","HS"))
(resOrd_hsint <- hs.int[order(hs.int$padj), ])

write.csv(resOrd_hsint, file= 
          "../../processed/DESEQ/treatment_HS_vs_C.csv",
          row.names=TRUE)


```





# Notes
# Note: https://www.biostars.org/p/320132/

```{r}
# Filter step not necessary; default in results() - see ?results, but enhances speed https://support.bioconductor.org/p/65256/
#filter <- rowSums(nc >= 10) >= 5 # at least 10 reads in at least 5 samples

# Increase the maximum iterations (maxit) instead of running DESeq()
#dds <- estimateSizeFactors(ddsDE_filt)
#dds <- estimateDispersions(dds)
#dds <- nbinomWaldTest(dds, maxit=20000)

# To remove the non-converging rows
#ddsClean <- dds[which(mcols(dds)$betaConv),]


## Merge with normalized count data
#res.dds_body <- merge(as.data.frame(res.dds), 
                       #as.data.frame(counts(dds_deseq, normalized=TRUE)), 
                       #by="row.names", sort=FALSE)
#names(res.dds_table)[1] <- "Gene"
#res.dds_body[,1] <- NULL

```
