---
title: "WGCNA_ANOVA and GO analysis"
author: "Enoch Ng'oma"
date: "4/8/2019"
output:
  html_document:
    theme: flatly
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(WGCNA)
library(tidyverse)
library(cowplot)
library(AnnotationDbi)
library(org.Dm.eg.db)

```

# Modules for the full dataset

```{r}

# Full dataset

# Load module names
load("../../processed/DESEQ/Coexpression/modules.RData")

# Read in multiple files by wildcard expansion on file paths
getMods <- lapply(Sys.glob(
  "../../processed/DESEQ/Coexpression/Mods/fbgn_names/*.txt",),read.table)

# Rename column
ss <- "FBgn"
for (i in 1:length(getMods)) {
 colnames(getMods[[i]]) <- ss 
}

# Add column for module name to each module
getMods <- mapply(cbind, getMods, "mod"=sort(modNames), 
                  SIMPLIFY=FALSE)
 
# Merge modules in list into one table (12569 + 45 grey)
ll <- bind_rows(getMods)

# Resampled data

# Genes uniquely assigned to module in less than half 50 of 100 datasets
droppedGenes <- read.csv("../../processed/DESEQ/Coexpression/Resamp_droppedGenes.csv")
colnames(droppedGenes)[2] <- "mod"

# Delete droppedGenes in ll
dd <- ll[!(ll$FBgn %in% droppedGenes$FBgn),]
str(dd)
str(ll)

# Move deleted genes to the grey module

lld <- ll[!(ll$FBgn %in% droppedGenes$FBgn),]
droppedGenes$mod <- "grey"
lld <- rbind(lld,droppedGenes)

```

# Compare module contents

```{r}
ll %>% 
  group_by(mod) %>%
  summarise(no_rows = length(mod)) %>%
  as.data.frame()
ll$analysis <- "full"

lld %>%
  group_by(mod) %>%
  summarise(no_rows = length(mod)) %>%
  as.data.frame()
lld$analysis <- "resamp"

# Differences
stlbl <- rbind(subset(ll, ll$mod=="steelblue"), subset(lld, lld$mod=="steelblue"))

```

# Gene Ontology on WGCNA modules

```{r}
# Modules & module names
load("../../processed/DESEQ/Coexpression/modules.RData")


# Output gene lists
# Fbgn annotation file "Genes:fbgn_annotation_ID_fb_2018_04.tsv"

annot = read.csv("../../processed/DESEQ/Coexpression/FlyAnnotation.csv")
dim(annot)
names(annot)
colnames(annot)[colnames(annot)=="X"] <- "FBgn"

rlogtrt <- read.csv("../../processed/DESEQ/rlogtrt_batchCor.csv")
rownames(rlogtrt) <- rlogtrt[,1]
FBgenes = as.data.frame(rownames(rlogtrt))
colnames(FBgenes)[colnames(FBgenes)=="rownames(rlogtrt)"] <- "FBgn"
FBgenes <- subset(FBgenes, FBgenes$FBgn %in% dd$FBgn)

FBgenes2annot = match(FBgenes$FBgn, annot$FBgn)
allIDs = annot$entrez[FBgenes2annot]


# Module GO term enrichment

# Enrichment table containing the 10 best terms for each module
GOenr <- GOenrichmentAnalysis(moduleColors, allIDs, 
                              organism = "fly", nBestP = 10)
tab <- GOenr$bestPTerms[[4]]$enrichment
names(tab)
write.csv(tab, file = "../../processed/DESEQ/Coexpression/resampMods/GOEnrichTab_Resamp.csv", 
              row.names = FALSE)
### Note message: GOenrichmentAnalysis: loading annotation data...
###  ..of the 12614  Entrez identifiers submitted, 10334 are mapped ###in current GO categories.
###  ..will use 10334 background genes for enrichment calculations.

# View table on screen
keepCols = c(1, 2, 5, 6, 7, 12, 13);
screenTab = tab[, keepCols];

# Round numeric columns to 2 decimal places:
numCols = c(3, 4);
screenTab[, numCols] = signif(apply(screenTab[, numCols], 2, as.numeric), 2)

# Truncate the the term name to at most 40 characters
screenTab[, 7] = substring(screenTab[, 7], 1, 40)

# Shorten the column names:
colnames(screenTab) = c("module", "size", "p-val", "Bonf", "nInTerm", "ont", "term name");
rownames(screenTab) = NULL;

# Set the width of R’s output
options(width=95)

# Enrichment table
screenTab
write.csv(screenTab, file = "../../processed/DESEQ/Coexpression/resampMods/GOEnrichTab_Resamp_simple.txt",
              row.names = FALSE)
```
