---
title: "GO Analysis"
author: "Enoch Ng'oma"
date: "October 6, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(GOplot)
library(tidyverse)
```

# Data

```{r}
# Fbgn annotation file "Genes:fbgn_annotation_ID_fb_2018_04.tsv"

FbAnnotIds <- read.csv("../../processed/DESEQ/fbgn_annotation_ID_fb_2018_04.csv",
                 stringsAsFactors = FALSE)

anotFbgn <- subset(FbAnnotIds, FbAnnotIds$organism_abbreviation=="Dmel")
anotFbgn <- select(anotFbgn, primary_FBgn, annotation_ID)
names(anotFbgn)[1]<-"Gene"
#anotFbgn$FBgn_ID <- toupper(anotFbgn$FBgn_ID)

# Dataframe of genes significant in the LRT test
sigInt <- read.csv("../../processed/DESEQ/DEGs_lrt.int_0.05.csv")
names(sigInt)[1]<-"FBgn_ID"
names(sigInt)[3] <- "logFC"
names(sigInt)[7] <- "adj.P.Val" 
#sigInt$FBgn_ID <- toupper(sigInt$FBgn_ID)

# Search and merge sigDEGs_int with filtered anotation file
sigInt <- right_join(anotFbgn, sigInt, by="FBgn_ID")

sigLrtTrt <- read.csv("../../processed/DESEQ/DEGs_lrt.treatment_0.05.csv")
names(sigLrtTrt)[1]<-"FBgn_ID"
names(sigLrtTrt)[3] <- "logFC"
names(sigLrtTrt)[7] <- "adj.P.Val" 
sigLrtTrt <- right_join(anotFbgn, sigLrtTrt, by="FBgn_ID")


# export files for GO in DAVID
dfile <- select(sigInt, FBgn_ID)
names(dfile) <- NULL
efile <- select(sigLrtTrt, FBgn_ID)
names(efile) <- NULL

write.csv(dfile, "../../processed/DESEQ/int_forDAVID.csv", row.names = FALSE)
write.csv(efile, "../../processed/DESEQ/CHS_forDAVID.csv", row.names = FALSE)

# Dataframe of DAVID Functional Annotation Chart (246 x 13)
func_anotChart_lrtTrt <- read.table("../../processed/DESEQ/Funct_Anot_Chart_lrtTrt.txt", 
                                 stringsAsFactors = FALSE, header = TRUE,sep = "\t")
```

# Prep Functional Annotation Chart Int Dataframe

```{r}
# sort by Category
anot.trt <- func_anotChart_int[order(func_anotChart_lrtTrt$Category), ]

# retain GO terms only
anot.trt <- anot.trt[grep('GOTERM_', anot.trt$Category),]

# remove excess chars from rownames
anot.trt <- anot.trt %>%
  mutate(Category = str_split(Category, "_", simplify = TRUE)[,2])

# split Term column
anot.trt <- separate(anot.trt, col = Term, into = c("FBgn_ID", "Term"), sep = "\\~")

# change multiple columns to factor
#names <- c('Category','FBgn_ID','Term','Genes')
#anot.trt[, names] <- lapply(anot.trt[, names], factor)

anot.trt <- select(anot.trt, Category, FBgn_ID, Term, Genes, Benjamini)
names(anot.trt)[5]<-"adj_pval"

```

# GOplot

```{r}
# Generate the plotting object
sigGenes <- select(sigInt, FBgn_ID, logFC)
sigLrtTrt <- select(sigLrtTrt, FBgn_ID, logFC)

circ <- circle_dat(anot.trt, sigGenes)
circa <- circle_dat(anot.trt, sigLrtTrt)

# A simple barplot
GOBar(subset(circ, category == 'BP'))

# Faceted barplot
GOBar(circ, display = 'multiple', title = 'Z-score coloured barplot', 
      zsc.col = c('yellow', 'black', 'cyan'))
```

# Bubble plot

```{r}
# Generate the bubble plot with a label threshold of 3
GOBubble(circ, labels = 3)

# Add a title, change the colour of the circles, facet the plot according to the categories and change the label threshold
GOBubble(circ, title = 'Bubble plot', colour = c('orange', 'darkred', 'gold'), display = 'multiple', labels = 3)

# Colour the background according to the category
GOBubble(circ, title = 'Bubble plot with background colour', display = 'multiple', bg.col = T, labels = 3)

# Reduce redundant terms with a gene overlap >= 0.75...
reduced_circ <- reduce_overlap(circ, overlap = 0.75)
# ...and plot it
GOBubble(reduced_circ, labels = 2.8)
```

# Circular visualization of the results of gene- annotation enrichment analysis (GOCircle)

```{r}
# Generate a circular visualization of the results of gene- annotation enrichment analysis
GOCircle(circ, nsub=12)

# Generate a circular visualization of selected terms
FBgn_IDs <- c('GO:005514', 'GO:0005975', 'GO:0006730', 'GO:0006508', 'GO:0046323')
GOCircle(circ, nsub = IDs)

# Generate a circular visualization for 10 terms (care!)
#GOCircle(circ, nsub = 10)
```

# Display of the relationship between genes and terms (GOChord)

```{r}
# Define a list of genes which you think are interesting to look at. The item EC$genes of the toy 
# sample contains the data frame of selected genes and their logFC. Have a look...
head(sigInt)
sigGenes <- subset(sigGenes, sigGenes$logFC>=1.5)
#sigGenes <- sigGenes[1:37,]

# select some of the significant enriched processes
eproc <- c('oxidation-reduction process',
           'carbohydrate metabolic process',
           'one-carbon metabolic process',
           'proteolysis',
           'glucose import',
           'hexose transmembrane transport',
           'glucose homeostasis')

# binary matrix
chord <- chord_dat(circ, sigGenes, eproc)

# Generate the matrix with a list of selected genes
chord <- chord_dat(data = circ, genes = sigGenes)

# Generate the matrix with selected processes
chord <- chord_dat(data = circ, process = eproc)

# Create the plot
#chord <- as.data.frame(chord)
GOChord(chord, space = 0.02, 
        #gene.order = 'logFC',
        nlfc=0, 
        gene.space = 0.25, 
        gene.size = 5, 
        process.label=5)

```

# Heatmap of genes and terms (GOHeat)

```{r}
# First, we use the chord object without logFC column to create the heatmap
GOHeat(chord[,-8], nlfc = 0)
GOHeat(chord, nlfc = 0, fill.col = c('red', 'yellow', 'green'))
```

# Golden eye (GOCluster)

```{r}
GOCluster(circ, eproc, clust.by = 'logFC',nlfc=0, term.width = 2)
GOCluster(circ, eproc, clust.by = 'term', lfc.col = c('darkgoldenrod1', 'black', 'cyan1'))
```

# Venn diagram (GOVenn)

```{r}
l1 <- subset(circ, term == 'oxidation-reduction process', c(sigGenes,logFC))
l2 <- subset(circ, term == 'carbohydrate metabolic process', c(sigGenes,logFC))
l3 <- subset(circ, term == 'glucose import', c(sigGenes,logFC))
GOVenn(l1,l2,l3, label = c('oxidation-reduction process', 'carbohydrate metabolic process', 'glucose import'))
```





