---
title: "Gene set analysis"
author: "Enoch Ng'oma"
date: "12/20/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(DESeq2)
library(tidyverse)
library(gage)
library(pathview)
library(AnnotationDbi)

# Get Dmel gene annotation database
library(org.Dm.eg.db)

```

# Set up kegg and GO gene sets

```{r}
columns(org.Dm.eg.db)

# Generate up-to-date KEGG pathway gene sets 
kegg_sets <- kegg.gsets(species = "dme", id.type = "entrez", check.new=FALSE)

# check that expr data and gene sets both use entrez
lapply(kegg_sets[1:3],head)
head(kegg_sets[[1]])

# sigmet.idx: signaling or metabolisms pathways
kegg_sets.dm = kegg_sets$kg.sets[kegg_sets$sigmet.idx]
head(kegg_sets.dm, 3)

#kegg.sets.dm = id.map.fb[kegg.sets$sigmet.idx]

# Generate up-to-date GO (Gene Ontology) gene sets
go_sets <- go.gsets(species = "Fly", 
                    pkg.name="org.Dm.eg.db", 
                    id.type = "eg", 
                    keep.evidence=FALSE)

# Do GO on Biological Process only (i.e. see ...$go.subs)
gobpsets = go_sets$go.sets[go_sets$go.subs$BP]
```

# Get Expression Data
# DESeq2-GAGE workflow
# need libraries: gage, pathview and org.Dm.eg.db
# Used this tutorial together with all 3 vignettes: http://www.gettinggeneticsdone.com/2015/12/tutorial-rna-seq-differential.html

```{r}

load(file="../../processed/DESEQ/all_fc_dat.rda")
head(rownames(all.fc.dat))

# Add annotation maps to results object

# gene symbol
all.fc.dat$symbol = mapIds(org.Dm.eg.db,
                     keys=row.names(all.fc.dat), 
                     column="SYMBOL",
                     keytype="FLYBASE",
                     multiVals="first")

# entrez id
all.fc.dat$entrez = mapIds(org.Dm.eg.db,
                     keys=row.names(all.fc.dat), 
                     column="ENTREZID",
                     keytype="FLYBASE",
                     multiVals="first")

# full gene name
all.fc.dat$name =   mapIds(org.Dm.eg.db,
                     keys=row.names(all.fc.dat), 
                     column="GENENAME",
                     keytype="FLYBASE",
                     multiVals="first")

head(all.fc.dat, 10)
head(all.fc.dat$symbol)

```

# Pathway anaylsis with GAGE
# Aim: enriched pathways

```{r}
cc.sets <- c("FC_DR_B","FC_DR_O","FC_DR_H",
             "FC_HS_B","FC_HS_O","FC_HS_H",
             "FC_DRHS_B","FC_DRHS_O","FC_DRHS_H")

e.names <- all.fc.dat$entrez

all.fc.dat <- all.fc.dat[,cc.sets]

out.list <- vector(mode='list', length=length(cc.sets))
names(out.list)  <- cc.sets

for (ii in 1:length(cc.sets)) 
  {

  fc.i <- all.fc.dat[,ii]
  names(fc.i) <- e.names

  fc.kegg = gage(fc.i, gsets = kegg_sets.dm, same.dir = TRUE)
  #  sel.up <- fc.kegg$greater[, "q.val"] < 0.1 &
  #         !is.na(fc.kegg$greater[, "q.val"])
  # path.ids.up <- rownames(fc.kegg$greater)[sel.up]
  # sel.down <- fc.kegg$less[, "q.val"] < 0.1 &
  #            !is.na(fc.kegg$less[,"q.val"])
  # path.ids.dwn <- rownames(fc.kegg$less)[sel.down]
  # path.ids2 <- substr(c(path.ids.up, path.ids.dwn), 1, 8)

#view first 3 pathways 
#pv.out.list <- sapply(path.ids2[1:3], function(pid) pathview(
#                        gene.data =  fc.i, pathway.id = pid,
#                        species = "dme", out.suffix=out.suffix))
  
out.list[[ii]] <- fc.kegg
}
lapply(out.list[[ii]], head)

#xx <- do.call(rbind, out.list)
#lj <- mapply(function(a,b) length(intersect(a,b)), 
#out.list$FC_DR_B$greater, out.list$FC_DR_O$greater, SIMPLIFY = FALSE)
#lk <- which(lj>0)
```

# Get all enriched pathways

```{r}
# up.DR_B <- subset(out.list$FC_DR_B$greater, 
#                      out.list$FC_DR_B$greater[,"q.val"] < 0.1)%>%
#   as.data.frame()

up.DR_B <- subset(out.list$FC_DR_B$greater)%>%as.data.frame()%>%add_column(compare = "up.DR_B")
up.DR_B <- rownames_to_column(up.DR_B, "pathway")%>%
  dplyr::select(pathway,stat.mean,q.val,set.size,compare)
dn.DR_B <- subset(out.list$FC_DR_B$less)%>%as.data.frame()%>%add_column(compare = "dn.DR_B")
dn.DR_B <- rownames_to_column(dn.DR_B, "pathway")%>%
  dplyr::select(pathway,stat.mean,q.val,set.size,compare)
up.DR_O <- subset(out.list$FC_DR_O$greater)%>%as.data.frame()%>%add_column(compare = "up.DR_O")
up.DR_O <- rownames_to_column(up.DR_O, "pathway")%>%
  dplyr::select(pathway,stat.mean,q.val,set.size,compare)
dn.DR_O <- subset(out.list$FC_DR_O$less)%>%as.data.frame()%>%add_column(compare = "dn.DR_O")
dn.DR_O <- rownames_to_column(dn.DR_O, "pathway")%>%
  dplyr::select(pathway,stat.mean,q.val,set.size,compare)
up.DR_H <- subset(out.list$FC_DR_H$greater)%>%as.data.frame()%>%add_column(compare = "up.DR_H")
up.DR_H <- rownames_to_column(up.DR_H, "pathway")%>%
  dplyr::select(pathway,stat.mean,q.val,set.size,compare)
dn.DR_H <- subset(out.list$FC_DR_H$less)%>%as.data.frame()%>%add_column(compare = "dn.DR_H")
dn.DR_H <- rownames_to_column(dn.DR_H, "pathway")%>%
  dplyr::select(pathway,stat.mean,q.val,set.size,compare)

up.HS_B <- subset(out.list$FC_HS_B$greater)%>%as.data.frame()%>%add_column(compare = "up.HS_B")
up.HS_B <- rownames_to_column(up.HS_B, "pathway")%>%
  dplyr::select(pathway,stat.mean,q.val,set.size,compare)
dn.HS_B <- subset(out.list$FC_HS_B$less)%>%as.data.frame()%>%add_column(compare = "dn.HS_B")
dn.HS_B <- rownames_to_column(dn.HS_B, "pathway")%>%
  dplyr::select(pathway,stat.mean,q.val,set.size,compare)
up.HS_O <- subset(out.list$FC_HS_O$greater)%>%as.data.frame()%>%add_column(compare = "up.HS_O")
up.HS_O <- rownames_to_column(up.HS_O, "pathway")%>%
  dplyr::select(pathway,stat.mean,q.val,set.size,compare)
dn.HS_O <- subset(out.list$FC_HS_O$less)%>%as.data.frame()%>%add_column(compare = "dn.HS_O")
dn.HS_O <- rownames_to_column(dn.HS_O, "pathway")%>%
  dplyr::select(pathway,stat.mean,q.val,set.size,compare)
up.HS_H <- subset(out.list$FC_HS_H$greater)%>%as.data.frame()%>%add_column(compare = "up.HS_H")
up.HS_H <- rownames_to_column(up.HS_H, "pathway")%>%
  dplyr::select(pathway,stat.mean,q.val,set.size,compare)
dn.HS_H <- subset(out.list$FC_HS_H$less)%>%as.data.frame()%>%add_column(compare = "dn.HS_H")
dn.HS_H <- rownames_to_column(dn.HS_H, "pathway")%>%
  dplyr::select(pathway,stat.mean,q.val,set.size,compare)

up.DRHS_B <- subset(out.list$FC_DRHS_B$greater)%>%as.data.frame()%>%add_column(compare = "up.DRHS_B")
up.DRHS_B <- rownames_to_column(up.DRHS_B, "pathway")%>%
  dplyr::select(pathway,stat.mean,q.val,set.size,compare)
dn.DRHS_B <- subset(out.list$FC_DRHS_B$less)%>%as.data.frame()%>%add_column(compare = "dn.DRHS_B")
  dn.DRHS_B <- rownames_to_column(dn.DRHS_B, "pathway")%>%
  dplyr::select(pathway,stat.mean,q.val,set.size,compare)
up.DRHS_O <- subset(out.list$FC_DRHS_O$greater)%>%as.data.frame()%>%add_column(compare = "up.DRHS_O")
up.DRHS_O <- rownames_to_column(up.DRHS_O, "pathway")%>%
  dplyr::select(pathway,stat.mean,q.val,set.size,compare)
dn.DRHS_O <- subset(out.list$FC_DRHS_O$less)%>%as.data.frame()%>%add_column(compare = "dn.DRHS_O")
dn.DRHS_O <- rownames_to_column(dn.DRHS_O, "pathway")%>%
  dplyr::select(pathway,stat.mean,q.val,set.size,compare)
up.DRHS_H <- subset(out.list$FC_DRHS_H$greater)%>%as.data.frame()%>%add_column(compare = "up.DRHS_H")
up.DRHS_H <- rownames_to_column(up.DRHS_H, "pathway")%>%
  dplyr::select(pathway,stat.mean,q.val,set.size,compare)
dn.DRHS_H <- subset(out.list$FC_DRHS_H$less)%>%as.data.frame()%>%add_column(compare = "dn.DRHS_H")
dn.DRHS_H <- rownames_to_column(dn.DRHS_H, "pathway")%>%
  dplyr::select(pathway,stat.mean,q.val,set.size,compare)

enrich.path <- rbind(up.DR_B,dn.DR_B,up.DR_O,dn.DR_O,up.DR_H,dn.DR_H,
                     up.HS_B,dn.HS_B,up.HS_O,dn.HS_O,up.HS_H,dn.HS_H,
                     up.DRHS_B,dn.DRHS_B,up.DRHS_O,dn.DRHS_O,up.DRHS_H,dn.DRHS_H)
```

# Filter

```{r}
# Pathways that differ by diet globally
ids <- strsplit(enrich.path$compare, split = "_", fixed = TRUE)
ids <- unlist(lapply(ids, function(x) x[1]))
enrich.path$diet <- ids
enrich.path$diet <- gsub('DRHS', 'DH', enrich.path$diet)
(enrich.path <- enrich.path[order(enrich.path$q.val), ])
#dup <- enrich.path[duplicated(enrich.path), ]

# qval < 0.05
pqval05 <- subset(enrich.path,enrich.path$q.val<0.05)
pqval05 <- pqval05[order(pqval05$compare),]
unq05 <- unique(pqval05$pathway)

# view one pathway
x <- subset(enrich.path,c(enrich.path$diet=="dn.HS" & 
                            enrich.path$pathway=="dme01200 Carbon metabolism"))
x <- x[order(x$pathway),]



#y <- subset(enrich.path, diet == "up.HS_B"|q.val <=0.05)
#xy <- which(x$pathway %in% y$pathway)

#glob_up.DR_HS <- subset(enrich.path, glob_up.DR_HS>0)
```


# Gene Ontology (GO)

```{r}
go.list <- vector(mode='list', length=length(cc.sets))
names(go.list)  <- cc.sets

for (kk in 1:length(cc.sets)) 
  {

  fc.k <- all.fc.dat[,kk]
  names(fc.k) <- e.names

  gobpres = gage(fc.k, gsets=gobpsets, same.dir=TRUE)
go.list[[kk]] <- gobpres
}

lapply(go.list[[kk]], head)
```

# Get enriched GO terms

```{r}
goup.DR_B <- subset(go.list$FC_DR_B$greater)%>%as.data.frame()%>%add_column(compare = "goup.DR_B")
goup.DR_B <- rownames_to_column(goup.DR_B, "goterm")%>%
  dplyr::select(goterm,stat.mean,q.val,set.size,compare)
godn.DR_B <- subset(go.list$FC_DR_B$less)%>%as.data.frame()%>%add_column(compare = "godn.DR_B")
godn.DR_B <- rownames_to_column(godn.DR_B, "goterm")%>%
  dplyr::select(goterm,stat.mean,q.val,set.size,compare)
goup.DR_O <- subset(go.list$FC_DR_O$greater)%>%as.data.frame()%>%add_column(compare = "goup.DR_O")
goup.DR_O <- rownames_to_column(goup.DR_O, "goterm")%>%
  dplyr::select(goterm,stat.mean,q.val,set.size,compare)
godn.DR_O <- subset(go.list$FC_DR_O$less)%>%as.data.frame()%>%add_column(compare = "godn.DR_O")
godn.DR_O <- rownames_to_column(godn.DR_O, "goterm")%>%
  dplyr::select(goterm,stat.mean,q.val,set.size,compare)
goup.DR_H <- subset(go.list$FC_DR_H$greater)%>%as.data.frame()%>%add_column(compare = "goup.DR_H")
goup.DR_H <- rownames_to_column(goup.DR_H, "goterm")%>%
  dplyr::select(goterm,stat.mean,q.val,set.size,compare)
godn.DR_H <- subset(go.list$FC_DR_H$less)%>%as.data.frame()%>%add_column(compare = "godn.DR_H")
godn.DR_H <- rownames_to_column(godn.DR_H, "goterm")%>%
  dplyr::select(goterm,stat.mean,q.val,set.size,compare)

goup.HS_B <- subset(go.list$FC_HS_B$greater)%>%as.data.frame()%>%add_column(compare = "goup.HS_B")
goup.HS_B <- rownames_to_column(goup.HS_B, "goterm")%>%
  dplyr::select(goterm,stat.mean,q.val,set.size,compare)
godn.HS_B <- subset(go.list$FC_HS_B$less)%>%as.data.frame()%>%add_column(compare = "godn.HS_B")
godn.HS_B <- rownames_to_column(godn.HS_B, "goterm")%>%
  dplyr::select(goterm,stat.mean,q.val,set.size,compare)
goup.HS_O <- subset(go.list$FC_HS_O$greater)%>%as.data.frame()%>%add_column(compare = "goup.HS_O")
goup.HS_O <- rownames_to_column(goup.HS_O, "goterm")%>%
  dplyr::select(goterm,stat.mean,q.val,set.size,compare)
godn.HS_O <- subset(go.list$FC_HS_O$less)%>%as.data.frame()%>%add_column(compare = "godn.HS_O")
godn.HS_O <- rownames_to_column(godn.HS_O, "goterm")%>%
  dplyr::select(goterm,stat.mean,q.val,set.size,compare)
goup.HS_H <- subset(go.list$FC_HS_H$greater)%>%as.data.frame()%>%add_column(compare = "goup.HS_H")
goup.HS_H <- rownames_to_column(goup.HS_H, "goterm")%>%
  dplyr::select(goterm,stat.mean,q.val,set.size,compare)
godn.HS_H <- subset(go.list$FC_HS_H$less)%>%as.data.frame()%>%add_column(compare = "godn.HS_H")
godn.HS_H <- rownames_to_column(godn.HS_H, "goterm")%>%
  dplyr::select(goterm,stat.mean,q.val,set.size,compare)

goup.DRHS_B <- subset(go.list$FC_DRHS_B$greater)%>%as.data.frame()%>%add_column(compare = "goup.DRHS_B")
goup.DRHS_B <- rownames_to_column(goup.DRHS_B, "goterm")%>%
  dplyr::select(goterm,stat.mean,q.val,set.size,compare)
godn.DRHS_B <- subset(go.list$FC_DRHS_B$less)%>%as.data.frame()%>%add_column(compare = "godn.DRHS_B")
  godn.DRHS_B <- rownames_to_column(godn.DRHS_B, "goterm")%>%
  dplyr::select(goterm,stat.mean,q.val,set.size,compare)
goup.DRHS_O <- subset(go.list$FC_DRHS_O$greater)%>%as.data.frame()%>%add_column(compare = "goup.DRHS_O")
goup.DRHS_O <- rownames_to_column(goup.DRHS_O, "goterm")%>%
  dplyr::select(goterm,stat.mean,q.val,set.size,compare)
godn.DRHS_O <- subset(go.list$FC_DRHS_O$less)%>%as.data.frame()%>%add_column(compare = "godn.DRHS_O")
godn.DRHS_O <- rownames_to_column(godn.DRHS_O, "goterm")%>%
  dplyr::select(goterm,stat.mean,q.val,set.size,compare)
goup.DRHS_H <- subset(go.list$FC_DRHS_H$greater)%>%as.data.frame()%>%add_column(compare = "goup.DRHS_H")
goup.DRHS_H <- rownames_to_column(goup.DRHS_H, "goterm")%>%
  dplyr::select(goterm,stat.mean,q.val,set.size,compare)
godn.DRHS_H <- subset(go.list$FC_DRHS_H$less)%>%as.data.frame()%>%add_column(compare = "godn.DRHS_H")
godn.DRHS_H <- rownames_to_column(godn.DRHS_H, "goterm")%>%
  dplyr::select(goterm,stat.mean,q.val,set.size,compare)

enrich.goterm <- rbind(goup.DR_B,godn.DR_B,goup.DR_O,godn.DR_O,goup.DR_H,godn.DR_H,
                        goup.HS_B,godn.HS_B,goup.HS_O,godn.HS_O,goup.HS_H,godn.HS_H,
                        goup.DRHS_B,godn.DRHS_B,goup.DRHS_O,godn.DRHS_O,goup.DRHS_H,godn.DRHS_H)
```

# Filter GO terms

```{r}
# GO terms that differ by diet globally
its <- strsplit(enrich.goterm$compare, split = "_", fixed = TRUE)
its <- unlist(lapply(its, function(x) x[1]))
enrich.goterm$diet <- its
enrich.goterm$diet <- gsub('DRHS', 'DH', enrich.goterm$diet)
(enrich.goterm <- enrich.goterm[order(enrich.goterm$q.val), ])
#dup <- enrich.goterm[duplicated(enrich.goterm), ]

# qval < 0.05
gqval05 <- subset(enrich.goterm,enrich.goterm$q.val>0.05 & enrich.goterm$q.val<0.1)
gqval05 <- gqval05[order(gqval05$compare),]
ung05 <- unique(gqval05$goterm)

# view one pathway
z <- subset(enrich.goterm,c(enrich.goterm$diet=="dn.HS" & 
                            enrich.goterm$goterm=="GO:0005975 carbohydrate metabolic process"))
z <- z[order(x$goterm),]



#y <- subset(enrich.path, diet == "up.HS_B"|q.val <=0.05)
#xy <- which(x$pathway %in% y$pathway)

#glob_up.DR_HS <- subset(enrich.path, glob_up.DR_HS>0)
```


```{r}
# Get pre-built gene sets for Dmel from http://www.go2msig.org/cgi-bin/prebuilt.cgi
#gsets=readList("../../processed/DESEQ/GO/Drosophila_melanogaster_GSEA_GO_sets_all_symbols_highquality_April_2015.gmt")
#gsets[1:3]

#gsets=readList("../../processed/DESEQ/GO/GeneSets_Dmel.gmt")
#gsets[1:3]

# Convert gsets gene symbols to Entrez IDs
#data(egSymb)
#gsets.sym <- lapply(gsets, sym2eg)
#gsets.sym[1:3] # few associations - see Powell (2014)
```