---
title: "Controlled Vocabularies"
author: "Enoch Ng'oma"
date: "10/18/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data: Effect of treatment

```{r}
# Fbgn annotation file "Genes:fbgn_annotation_ID_fb_2018_04.tsv"

FbAnnotIds <- read.csv("../../processed/DESEQ/fbgn_annotation_ID_fb_2018_04.csv",
                 stringsAsFactors = FALSE)

anotFbgn <- subset(FbAnnotIds, FbAnnotIds$organism_abbreviation=="Dmel")
anotFbgn <- select(anotFbgn, primary_FBgn, annotation_ID)
names(anotFbgn)[1]<-"Gene"
#anotFbgn$FBgn_ID <- toupper(anotFbgn$FBgn_ID)

# Search and merge sigDEGs_int with filtered anotation file
sigInt <- right_join(anotFbgn, sigInt, by="FBgn_ID")

sigLrtTrt <- read.csv("../../processed/DESEQ/DEGs_lrt.treatment_0.05.csv")
names(sigLrtTrt)[1]<-"FBgn_ID"
names(sigLrtTrt)[3] <- "logFC"
names(sigLrtTrt)[7] <- "adj.P.Val" 
sigLrtTrt <- right_join(anotFbgn, sigLrtTrt, by="FBgn_ID")


# export files for GO in DAVID
dfile <- select(sigInt, FBgn_ID)
names(dfile) <- NULL
efile <- select(sigLrtTrt, FBgn_ID)
names(efile) <- NULL

write.csv(dfile, "../../processed/DESEQ/int_forDAVID.csv", row.names = FALSE)
write.csv(efile, "../../processed/DESEQ/CHS_forDAVID.csv", row.names = FALSE)

# Dataframe of DAVID Functional Annotation Chart (246 x 13)
func_anotChart_lrtTrt <- read.table("../../processed/DESEQ/Funct_Anot_Chart_lrtTrt.txt", 
                                 stringsAsFactors = FALSE, header = TRUE,sep = "\t")
```

# Prep Functional Annotation Chart Treatment Dataframe

```{r}
# sort by Category
anot.trt <- func_anotChart_lrtTrt[order(func_anotChart_lrtTrt$Category), ]

# retain GO terms only
anot.trt <- anot.trt[grep('GOTERM_', anot.trt$Category),]

# remove excess chars from rownames
anot.trt <- anot.trt %>%
  mutate(Category = str_split(Category, "_", simplify = TRUE)[,2])

# split Term column
anot.trt <- separate(anot.trt, col = Term, into = c("FBgn_ID", "Term"), sep = "\\~")

anot.trt <- select(anot.trt, Category, FBgn_ID, Term, Genes, Benjamini)
names(anot.trt)[5]<-"adj_pval"

```

# Controlled Vocabularies (GO terms)

```{r}
CVTerms <- read.csv("../../processed/DESEQ/CV_terms.csv",stringsAsFactors = FALSE)

#GO:0007568 - aging
age <- subset(CVTerms, CVTerms$GO_cat=="aging")
age.treat <- merge_treat %>%
      filter(FBgn %in% age$FBgn)
age.int <- merge_int %>%
  filter(FBgn %in% age$FBgn)
age.treat$effect <- "treat"
age.int$effect <- "int"
AGE <- rbind(age.treat,age.int)

#GO:0008340 - determination of adult lifespan
doal <- subset(CVTerms, CVTerms$GO_cat=="det_adul_life")
doal.treat <- merge_treat %>%
      filter(FBgn %in% doal$FBgn)
doal.int <- merge_int %>%
  filter(FBgn %in% doal$FBgn)
doal.treat$effect <- "treat"
doal.int$effect <- "int"
DOAL <- rbind(doal.treat,doal.int)

#GO:0008286 - insulin receptor signaling pathway
irsp <- subset(CVTerms, CVTerms$GO_cat=="IR_sig_path")
irsp <- merge_treat %>%
      filter(FBgn %in% irsp$FBgn)
irsp.int <- merge_int %>%
  filter(FBgn %in% irsp$FBgn)
irsp$effect <- "treat"
irsp.int$effect <- "int"
IRSP <- rbind(irsp,irsp.int)

#GO:0042593 - glucose homeostasis
gluc <- subset(CVTerms, CVTerms$GO_cat=="gluc_homeo")
gluc.treat <- merge_treat %>%
      filter(FBgn %in% gluc$FBgn)
gluc.int <- merge_int %>%
  filter(FBgn %in% gluc$FBgn)
gluc.treat$effect <- "treat"
gluc.int$effect <- "int"
GLUC <- rbind(gluc.treat,gluc.int)

#GO:0006629 - lipid metabolic process
lipmetp <- subset(CVTerms, CVTerms$GO_cat=="lip_met_proc")
lipmetp.treat <- merge_treat %>%
      filter(FBgn %in% lipmetp$FBgn)
lipmetp.int <- merge_int %>%
  filter(FBgn %in% lipmetp$FBgn)
lipmetp.treat$effect <- "treat"
lipmetp.int$effect <- "int"
LIPMETP <- rbind(lipmetp.treat,lipmetp.int)

#GO:0010897 - negative regulation of triglyceride catabolic process
nrtcp <- subset(CVTerms, CVTerms$GO_cat=="negRegl_trigly_catProc")
nrtcp.treat <- merge_treat %>%
      filter(FBgn %in% nrtcp$FBgn)
nrtcp.int <- merge_int %>%
  filter(FBgn %in% nrtcp$FBgn)
# zero

#GO:0042594 - response to starvation
rstarv <- subset(CVTerms, CVTerms$GO_cat=="resp_to_starv")
rstarv.treat <- merge_treat %>%
      filter(FBgn %in% rstarv$FBgn)
rstarv.int <- merge_int %>%
  filter(FBgn %in% rstarv$FBgn)
rstarv.treat$effect <- "treat"
rstarv.int$effect <- "int"
RSTARV <- rbind(rstarv.treat,rstarv.int)

#GO:0009267 - cellular response to starvation
crts <- subset(CVTerms, CVTerms$GO_cat=="cell_resp_starv")
crts.treat <- merge_treat %>%
      filter(FBgn %in% crts$FBgn)
crts.int <- merge_int %>%
  filter(FBgn %in% crts$FBgn)
crts.treat$effect <- "treat"
#crts.int$effect <- "int"
#CRTS <- rbind(crts.treat,crts.int)

```

# Nutrient-sensing pathways

```{r}
# IIS/TOR
iis_stan <- read.csv("../../processed/DESEQ/iisprobe_gene_CG_decoder.csv",stringsAsFactors = FALSE)

colnames(iis_stan)[2] <- "gname"
trt <- inner_join(iis_stan,merge_treat, by="gname")
trt$effect <- "treat"

xk <- merge_treat
colnames(xk)[10] <- "CG"
trt1 <- inner_join(iis_stan,xk, by="CG")

int <- inner_join(iis_stan,merge_int, by="gname")
int$effect <- "intr"

iis_tor <- rbind(trt,int)
```

