---
title: "Visualizing DE of Base Population RNASeq using DESeq2"
author: "Enoch Ng'oma"
date: "10/21/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(DESeq2)
library(tidyverse)
library(cowplot)

source("modified_plotPCA_function.R")
set.seed(354902)
```

# Data

```{r}
# Sample info with surrogate variable
phenDat.sva <- read.csv("../../processed/DESEQ/sampleDat_with_SV.csv")
rownames(phenDat.sva) <- phenDat.sva[,1]
phenDat.sva[,1] <- NULL
phenDat.sva$batch <- as.factor(phenDat.sva$batch)

# Expression matrix
expr_viz <- read.csv("../../processed/DESEQ/normExpr_countData.csv")
rownames(expr_viz) <- expr_viz[,1]
expr_viz[,1] <- NULL
expr_viz <- as.matrix(expr_viz)

```

# Fit DESeq models

```{r}
dds.01 <- DESeqDataSetFromMatrix(countData = expr_viz, 
                                   colData = phenDat.sva, 
                                   design = ~ SV1 + batch + tissue + treatment)
dds_deseq.01 <- estimateSizeFactors(dds.01)
nc <- counts(dds_deseq.01, normalized=TRUE)
filter <- rowSums(nc >= 10) >= 2
dds_deseq.01 <- dds_deseq.01[filter,]
dds_deseq.01 <- estimateDispersions(dds_deseq.01, fitType = "local")
dds_deseq.01 <- nbinomWaldTest(dds_deseq.01, maxit = 1000, useOptim = TRUE)

resultsNames(dds_deseq.01)

# Look at the DESeq object
colData(dds_deseq.01)
#save(dds_deseq.01, file="../../processed/DESEQ/dds_deseq01.Rda")
load("../../processed/DESEQ/dds_deseq01.Rda")

dds.02 <- DESeqDataSetFromMatrix(countData = expr_viz, 
                                   colData = phenDat.sva, 
                                   design = ~ SV1 + batch + tissue*treatment)

dds_deseq.02 <- estimateSizeFactors(dds.02)
nc <- counts(dds_deseq.02, normalized=TRUE)
filter <- rowSums(nc >= 10) >= 2
dds_deseq.02 <- dds_deseq.02[filter,]
dds_deseq.02 <- estimateDispersions(dds_deseq.02, fitType = "local")
dds_deseq.02 <- nbinomWaldTest(dds_deseq.02, maxit = 1000, useOptim = TRUE)
dds_deseq.02 <- dds_deseq.02[which(mcols(dds_deseq.02)$betaConv),]

resultsNames(dds_deseq.02)
colData(dds_deseq.02)

# Test if all values are equal
#which(all(dds_deseq.01 != dds_deseq.02))

# Test if objects are identical
identical(dds_deseq.01,dds_deseq.02)
#save(dds_deseq.02, file="../../processed/DESEQ/dds_deseq.02.Rda")
load("../../processed/DESEQ/dds_deseq.02.Rda")
```

# PCA using DESeq2

```{r}
# vsd & rlog transform data on the log2 scale normalized to library size
# blind set to TRUE prevents re-estimation of size factors

vsd.01 <- varianceStabilizingTransformation(dds_deseq.01, blind = TRUE, fitType = "parametric")
vsd.02 <- varianceStabilizingTransformation(dds_deseq.02, blind = TRUE, fitType = "parametric")

# time intensive; incorporates a prior on the sample differences
# rlog fits a shrinkage term for each sample and each gene
# rlog shrinkage is greater for low counts and a much weaker effect for high counts (see ?rlog)
#rlog.01 <- rlog(dds_deseq.01, blind = TRUE, fitType = "parametric")
#rlog.02 <- rlog(dds_deseq.02, blind = TRUE, fitType = "parametric")
#save(rlog.01, file = "../../processed/DESEQ/rlogTransform_on_dds_deseq.01.Rda")
#save(rlog.02, file = "../../processed/DESEQ/rlogTransform_on_dds_deseq.02.Rda")
load("../../processed/DESEQ/rlogTransform_on_dds_deseq.01.Rda")
load("../../processed/DESEQ/rlogTransform_on_dds_deseq.02.Rda")

# Plot vsd
print(plotPCA(vsd.01, intgroup=c("treatment", "tissue")))
plotPCA(vsd.01, intgroup=c("treatment", "tissue"), returnData=FALSE)
plotPCA(vsd.02, intgroup=c("treatment", "tissue"), returnData=FALSE)
# not different

# PC1/PC2: Choose one variance stabilization (vst) plot 
pcaVsd <- plotPCA(vsd.02, intgroup=c("treatment", "tissue"), returnData=TRUE)
percentVar <- round(100 * attr(pcaVsd, "percentVar"))
ggplot(pcaVsd, aes(PC1, PC2, color=treatment, shape=tissue)) +
  geom_point(size=3) +
  theme(axis.title.y = element_text(size = 12),
                text = element_text(size = 12))+
  scale_color_manual(values=c("#999999", "#E69F00", "#56B4E9")) +
  xlab(paste0("PC1: ",percentVar[1],"% variance")) +
  ylab(paste0("PC2: ",percentVar[2],"% variance")) + 
  coord_fixed()
ggsave(last_plot(),file = "../../plots/PCAplot_vst_02.pdf",width = 5,height=5)


# Plot rlog
plotPCA(rlog.01, intgroup=c("treatment", "tissue"), returnData=FALSE)
plotPCA(rlog.02, intgroup=c("treatment", "tissue"), returnData=FALSE)
# not different

# PC1/PC2: Choose one regularized log transformation (rlog) plot
pcaData <- plotPCA(rlog.02, intgroup=c("treatment", "tissue"), returnData=TRUE)
percentVar <- round(100 * attr(pcaData, "percentVar"))
ggplot(pcaData, aes(PC1, PC2, color=treatment, shape=tissue)) +
  geom_point(size=3) +
  theme(axis.title.y = element_text(size = 12),
                text = element_text(size = 12))+
  scale_color_manual(values=c("#999999", "#E69F00", "#56B4E9")) +
  xlab(paste0("PC1: ",percentVar[1],"% variance")) +
  ylab(paste0("PC2: ",percentVar[2],"% variance")) + 
  coord_fixed()
(pcaData <- pcaData[order(pcaData$tissue), ])
ggsave(last_plot(),file = "../../plots/PCAplot_rlog_02.pdf",width = 5,height=5)

# PC3/PC4: source code modified
# ref: http://seqanswers.com/forums/showthread.php?t=66769
pc34 <- pcaPlot(rlog.02, intgroup=c("treatment", "tissue"), returnData=TRUE)
percentVar <- round(100 * attr(pc34, "percentVar"))

#print(pcaPlot(rlog.02, intgroup=c("treatment", "tissue")))

ggplot(pc34, aes(PC3, PC4, color=treatment, shape=tissue)) + 
  geom_point(size = 3) + 
  geom_point(size=3) +
  theme(axis.title.y = element_text(size = 12),
                text = element_text(size = 12))+
  scale_color_manual(values=c("#999999", "#E69F00", "#56B4E9")) +
  xlab(paste0("PC3: ", percentVar[3],"% variance")) + 
  ylab(paste0("PC4: ", percentVar[4],"% variance")) + 
  coord_fixed()

ggsave(last_plot(),file = "../../plots/PCAplot_rlog_02_PC3PC4.pdf",width = 5,height=5)

```

# PrComp
# do not use
#use scale = TRUE
```{r}
cPCA <- prcomp(t(expr_viz))
summary(cPCA)
propvar <- (cPCA$sdev^2) / (sum(cPCA$sdev^2))*100
barplot(propvar, cex.names=1, xlab=paste("Principal component (PC), 1-", length(cPCA$sdev)), ylab="Proportion of variation (%)", main="Scree plot", ylim=c(0,100))

par(cex=1.0, cex.axis=0.8, cex.main=0.8)
pairs(cPCA$x[,1:5], col="black", main="Principal components analysis bi-plot\nPCs 1-5", pch=16)
pairs(cPCA$x[,6:10], col="black", main="Principal components analysis bi-plot\nPCs 6-10", pch=16)


par(mar=c(4,4,4,4), mfrow=c(1,3), cex=1.0, cex.main=0.8, cex.axis=0.8)

#Plots scatter plot for PC 1 and 2
plot(cPCA$x, type="n", main="Principal components analysis bi-plot", xlab=paste("PC1, ", round(propvar[1], 2), "%"), ylab=paste("PC2, ", round(propvar[2], 2), "%"))
points(cPCA$x, col="black", pch=16, cex=1)

#Plots scatter plot for PC 1 and 3
plot(cPCA$x[,1], cPCA$x[,3], type="n", main="Principal components analysis bi-plot", xlab=paste("PC1, ", round(propvar[1], 2), "%"), ylab=paste("PC3, ", round(propvar[3], 2), "%"))
points(cPCA$x[,1], cPCA$x[,3], col="black", pch=16, cex=1)

#Plots scatter plot for PC 2 and 3
plot(cPCA$x[,2], cPCA$x[,3], type="n", main="Principal components analysis bi-plot", xlab=paste("PC2, ", round(propvar[2], 2), "%"), ylab=paste("PC3, ", round(propvar[3], 2), "%"))
points(cPCA$x[,2], cPCA$x[,3], col="black", pch=16, cex=1)
```

