---
title: "Removing batch effects in Base Population RNA-seq data"
author: "Enoch Ng'oma"
date: "6/14/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(sva)
library(pamr)
library(limma)
library(dplyr)
```

# Load data - all transcripts across tissues and diets

```{r}
# read extracted table
basep_all <- read.csv("../processed/results/ballG_all_results/gene_associated_texpr.csv", 
                    stringsAsFactors = FALSE)

phenDat <- read.csv("describe_samples.csv", stringsAsFactors = FALSE)

```

# Set up data for sva

```{r}
# 1. create model matrices using model.matrix()

  # variable of interest: treatment
  # data stored in bg_ballG_filt

# Phenotype variables 
phenDat = phenDat 

# Expression variables
basep_all = basep_all %>%
  select(-geneNames, -geneIDs) %>%
  select(tname, everything())

nams <- basep_all$tname
rownames(basep_all) = make.names(nams, unique=TRUE) 
basep_all$tname <- NULL

basep_all <- as.matrix(basep_all)

# Create a full model matrix
# at this point we have only var of interest, no adj. vars
# since treatment has multiple levels, treat it as factor
mod = model.matrix(~as.factor(treatment) + as.factor(tissue), data=phenDat)
```

# Apply sva() to estimate batch and other artifacts

```{r}
# Null model (i.e. only adj. vars)
# with no adjustment - just the intercept included
mod0 = model.matrix(~1, data=phenDat)

# a) get number of latent factors
#n.sv = num.sv(basep_all, mod, method = "leek")
n.sv = num.sv(basep_all, mod, method = "be", B=20, seed = 48)
n.sv

# b) estimage surrogate variables
svobj = sva(basep_all, mod, mod0, n.sv=n.sv, B = 20)

#svobj = sva(basep_all, mod, mod0) 
# errors, see:
# https://www.biostars.org/p/198820/
# What does this error mean? - issue implementing SVA
# https://stackoverflow.com/questions/43101585/error-when-generating-the-sva-object-using-package-sva-in-r

```

# Adjusting for surrogate variables - f.pvalue()

```{r}
# 1) First, calculate F-test p-values for DE wrt diet, without adjusting for SVs
pValues = f.pvalue(basep_all, mod, mod0)
qValues = p.adjust(pValues, method = "BH") 

# 2) Adjust for surrogates

# a) include surrogates in both full and null models, then get p-vals and q-vals
modSv = cbind(mod, svobj$sv) # sv is matrix whose columns are estimated SVs
mod0Sv = cbind(mod0, svobj$sv)
pValuesSv = f.pvalue(basep_all, modSv, mod0Sv)
qValuesSv = p.adjust(pValuesSv, method = "BH")

# These are the adjusted P-values and Q-values accounting for surrogate variables.
```

# Adjusting for surrogate variables using the limma package

```{r}
# 1) fit a linear model with surrogate variables
fit = lmFit(basep_all, modSv)

#From here, you can use the limma functions to perform the usual analyses.
```

# Suppose we want to calculate DE wrt diet ( with limma package)


```{r}
# 1) compute contrasts between pairs of diet terms
    # no surrogates included here since SVs are only useful for adjustment
contrast.matrix <- cbind("C1"=c(-1,1,0,rep(0,svobj$n.sv)),
                         "C2"=c(0,-1,1,rep(0,svobj$n.sv)),
                         "C3"=c(-1,0,1,rep(0,svobj$n.sv)))

fitContrasts = contrasts.fit(fit,contrast.matrix) 

# 2) calculate the test statistic using eBayes()
eb = eBayes(fitContrasts)
topTable(eb, adjust="BH")

```



